# Migrations do Supabase - Dashboard de Leads

## Como usar este arquivo

1. Acesse o Supabase Dashboard → SQL Editor
2. Copie e execute cada seção em ordem
3. Verifique se cada comando foi executado com sucesso antes de prosseguir

---

## 1. Criar Tipos ENUM

```sql
-- Status dos leads
CREATE TYPE lead_status AS ENUM (
  'em_atendimento',
  'nao_respondido',
  'em_negociacao',
  'fechado'
);

-- Tipos de mensagem
CREATE TYPE message_type AS ENUM (
  'text',
  'audio',
  'image',
  'pdf',
  'button',
  'list'
);

-- Remetente da mensagem
CREATE TYPE message_sender AS ENUM (
  'lead',
  'ai',
  'human'
);

-- Segmento de campanha
CREATE TYPE campanha_segmento AS ENUM (
  'fechados',
  'nao_fechados',
  'todos'
);
```

---

## 2. Criar Tabelas

### Tabela: produtos
```sql
CREATE TABLE produtos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  descricao TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

### Tabela: atendentes
```sql
CREATE TABLE atendentes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nome TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

### Tabela: leads
```sql
CREATE TABLE leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone TEXT UNIQUE NOT NULL,
  name TEXT,
  status lead_status DEFAULT 'em_atendimento',
  produto_interesse TEXT,
  atendente_responsavel TEXT,
  is_ai_active BOOLEAN DEFAULT true,
  is_urgent BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

### Tabela: messages (Formato N8N/LangChain)
```sql
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL, -- Corresponde ao telefone do lead
  message JSONB NOT NULL, -- Ex: { "type": "human", "content": "..." }
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

### Tabela: campanhas
```sql
CREATE TABLE campanhas (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL,
  mensagem TEXT NOT NULL,
  tempo_disparo TEXT NOT NULL, -- ex: '24 hours', '2 days'
  segmento TEXT NOT NULL, -- ex: 'nao_respondido', 'fechado'
  is_active BOOLEAN DEFAULT true,
  is_recurrent BOOLEAN DEFAULT false,
  recurrence_period INTEGER DEFAULT 3, -- em dias
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

### Tabela: metricas
```sql
CREATE TABLE metricas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  data DATE NOT NULL UNIQUE,
  total_leads INTEGER DEFAULT 0,
  taxa_fechamento DECIMAL(5,2) DEFAULT 0,
  tempo_medio_resposta INTERVAL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);
```

---

## 3. Criar Índices

```sql
-- Índices para a tabela leads
CREATE INDEX idx_leads_status ON leads(status);
CREATE INDEX idx_leads_urgent ON leads(is_urgent);
CREATE INDEX idx_leads_phone ON leads(phone);
CREATE INDEX idx_leads_created_at ON leads(created_at DESC);

-- Índices para a tabela messages
CREATE INDEX idx_messages_lead_id ON messages(lead_id);
CREATE INDEX idx_messages_created_at ON messages(created_at DESC);
```

---

## 4. Criar Triggers

```sql
-- Função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Função para criar lead automaticamente ao receber mensagem (Integração N8N)
CREATE OR REPLACE FUNCTION auto_create_lead_from_message()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO leads (phone, name, status, is_ai_active)
  VALUES (NEW.session_id, 'Novo Lead ' || NEW.session_id, 'nao_respondido', true)
  ON CONFLICT (phone) DO UPDATE 
  SET updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Aplicar trigger na tabela leads
CREATE TRIGGER update_leads_updated_at
  BEFORE UPDATE ON leads
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Aplicar trigger de auto-criação na tabela messages
CREATE TRIGGER trigger_auto_create_lead
  AFTER INSERT ON messages
  FOR EACH ROW
  EXECUTE FUNCTION auto_create_lead_from_message();
```

---

## 5. Desabilitar RLS (Single-Account Mode)

```sql
-- Desabilitar Row Level Security para single-account
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE produtos DISABLE ROW LEVEL SECURITY;
ALTER TABLE atendentes DISABLE ROW LEVEL SECURITY;
ALTER TABLE campanhas DISABLE ROW LEVEL SECURITY;
ALTER TABLE metricas DISABLE ROW LEVEL SECURITY;
```

---

## 6. Habilitar Realtime

```sql
-- Habilitar Realtime para updates em tempo real
ALTER PUBLICATION supabase_realtime ADD TABLE leads;
ALTER PUBLICATION supabase_realtime ADD TABLE messages;
```

---

## 7. Inserir Dados de Exemplo

### Produtos
```sql
INSERT INTO produtos (nome, descricao) VALUES
  ('Consórcio de Imóvel', 'Consórcio para aquisição de imóveis'),
  ('Consórcio de Automóvel', 'Consórcio para aquisição de veículos'),
  ('Carta de Crédito Contemplada', 'Cartas de crédito já contempladas'),
  ('Consórcio de Moto', 'Consórcio para aquisição de motocicletas'),
  ('Consórcio de Serviços', 'Consórcio para diversos serviços');
```

### Atendente Exemplo
```sql
INSERT INTO atendentes (nome, email) VALUES
  ('Equipe Vendas', 'vendas@empresa.com'),
  ('Suporte Técnico', 'suporte@empresa.com');
```

### Leads de Exemplo (opcional - para testes)
```sql
-- Inserir lead de exemplo
DO $$
DECLARE
  produto_id UUID;
BEGIN
  -- Pegar o ID do primeiro produto
  SELECT id INTO produto_id FROM produtos LIMIT 1;
  
  -- Inserir leads de teste
  INSERT INTO leads (phone, name, status, produto_interesse, is_urgent) VALUES
    ('+5511999999999', 'João Silva', 'em_atendimento', produto_id, true),
    ('+5511988888888', 'Maria Santos', 'em_negociacao', produto_id, false),
    ('+5511977777777', 'Carlos Oliveira', 'nao_respondido', produto_id, true);
END $$;
```

---

## 8. Verificar Instalação

```sql
-- Verificar se todas as tabelas foram criadas
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- Contar registros em cada tabela
SELECT 
  'leads' as tabela, COUNT(*) as total FROM leads
UNION ALL
SELECT 'messages', COUNT(*) FROM messages
UNION ALL
SELECT 'produtos', COUNT(*) FROM produtos
UNION ALL
SELECT 'atendentes', COUNT(*) FROM atendentes
UNION ALL
SELECT 'campanhas', COUNT(*) FROM campanhas
UNION ALL
SELECT 'metricas', COUNT(*) FROM metricas;
```

---

## ✅ Checklist de Execução

- [ ] Executar seção 1: Criar Tipos ENUM
- [ ] Executar seção 2: Criar Tabelas
- [ ] Executar seção 3: Criar Índices
- [ ] Executar seção 4: Criar Triggers
- [ ] Executar seção 5: Desabilitar RLS
- [ ] Executar seção 6: Habilitar Realtime
- [ ] Executar seção 7: Inserir Dados de Exemplo
- [ ] Executar seção 8: Verificar Instalação

**Status**: Todas as queries devem executar sem erros!
